name: Deploy AI Image

on:
  workflow_run:
    workflows:
      - 'Build AI Image'
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.DOCKER_UPLOAD_TOKEN }}

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_PASS }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd /app/ai
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} docker compose -f docker-compose.prod.yml up --build
