name: Deploy AI Image

on:
  workflow_run:
    workflows:
      - 'Build AI Image'
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_PASS }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd /app/ai
          docker login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.DOCKER_UPLOAD_TOKEN }}
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} docker compose -f docker-compose.prod.yml up --build
